swagger: "2.0"
info:
  title: Salud API
  description: Api para el módulo de Salud del proyecto SIBUD
  version: 1.0.0
  termsOfService: http://www.udistrital.edu.co/politicas-de-privacidad.pdf
  contact:
    email: baluist@correo.udistrital.edu.co
  license:
    name: BSD-3-Clause
    url: http://opensource.org/licenses/BSD-3-Clause
basePath: /v1
paths:
  /accesoHistoria/:
    get:
      tags:
      - accesoHistoria
      description: consulta todos los registros de la tabla AccesoHistoriaClinica
      operationId: AccesoHistoriaClinicaController.Get All
      parameters:
      - in: consulta
        name: query
        description: 'Filtro. Por ejemplo, col1: v1, col2: v2 ...'
        type: string
      - in: consulta
        name: fields
        description: Campos devueltos. Por ejemplo, col1, col2 ...
        type: string
      - in: consulta
        name: sortby
        description: Campos ordenados por. Por ejemplo, Col1, col2 ...
        type: string
      - in: consulta
        name: order
        description: El orden correspondiente a cada campo de clasificación, si es un valor único, se aplica a todos los campos de clasificación. Por ejemplo, desc, asc ...
        type: string
      - in: consulta
        name: limit
        description: Limite el tamaño del conjunto de resultados. Debe ser un número entero
        type: string
      - in: consulta
        name: offset
        description: Posición inicial del conjunto de resultados. Debe ser un número entero
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.AccesoHistoriaClinica'
        "403":
          description: ""
    post:
      tags:
      - accesoHistoria
      description: agregar un registro en la tabla AccesoHistoriaClinica
      operationId: AccesoHistoriaClinicaController.Post
      parameters:
      - in: body
        name: body
        description: Cuerpo para el contenido de AccesoHistoriaClinica
        required: true
        schema:
          $ref: '#/definitions/models.AccesoHistoriaClinica'
      responses:
        "201":
          description: '{int} models.AccesoHistoriaClinica'
        "403":
          description: Cuerpo Vacío
  /accesoHistoria/{id}:
    get:
      tags:
      - accesoHistoria
      description: consultar un registro de la tabla AccesoHistoriaClinica por su id
      operationId: AccesoHistoriaClinicaController.Get One
      parameters:
      - in: path
        name: id
        description: Id a consultar
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.AccesoHistoriaClinica'
        "403":
          description: :id está vacío
    put:
      tags:
      - accesoHistoria
      description: actualizar un registro de la tabla AccesoHistoriaClinica
      operationId: AccesoHistoriaClinicaController.Put
      parameters:
      - in: path
        name: id
        description: Id del registro a actualizar
        required: true
        type: string
      - in: body
        name: body
        description: Cuerpo para el contenido de AccesoHistoriaClinica
        required: true
        schema:
          $ref: '#/definitions/models.AccesoHistoriaClinica'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.AccesoHistoriaClinica'
        "403":
          description: :id no es entero
    delete:
      tags:
      - accesoHistoria
      description: elimina un registro de la tabla AccesoHistoriaClinica
      operationId: AccesoHistoriaClinicaController.Delete
      parameters:
      - in: path
        name: id
        description: Id del registro a eliminar
        required: true
        type: string
      responses:
        "200":
          description: '{string} borrado exitoso!'
        "403":
          description: Id vacío
  /medicinaAntecedente/:
    get:
      tags:
      - medicinaAntecedente
      description: consulta todos los registros de la tabla MedicinaAntecedente
      operationId: MedicinaAntecedenteController.Get All
      parameters:
      - in: consulta
        name: query
        description: 'Filtro. Por ejemplo, col1: v1, col2: v2 ...'
        type: string
      - in: consulta
        name: fields
        description: Campos devueltos. Por ejemplo, col1, col2 ...
        type: string
      - in: consulta
        name: sortby
        description: Campos ordenados por. Por ejemplo, Col1, col2 ...
        type: string
      - in: consulta
        name: order
        description: El orden correspondiente a cada campo de clasificación, si es un valor único, se aplica a todos los campos de clasificación. Por ejemplo, desc, asc ...
        type: string
      - in: consulta
        name: limit
        description: Limite el tamaño del conjunto de resultados. Debe ser un número entero
        type: string
      - in: consulta
        name: offset
        description: Posición inicial del conjunto de resultados. Debe ser un número entero
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.MedicinaAntecedente'
        "403":
          description: ""
    post:
      tags:
      - medicinaAntecedente
      description: agregar un registro en la tabla MedicinaAntecedente
      operationId: MedicinaAntecedenteController.Post
      parameters:
      - in: body
        name: body
        description: Cuerpo para el contenido de MedicinaAntecedente
        required: true
        schema:
          $ref: '#/definitions/models.MedicinaAntecedente'
      responses:
        "201":
          description: '{int} models.MedicinaAntecedente'
        "403":
          description: Cuerpo Vacío
  /medicinaAntecedente/{id}:
    get:
      tags:
      - medicinaAntecedente
      description: consultar un registro de la tabla MedicinaAntecedente por su id
      operationId: MedicinaAntecedenteController.Get One
      parameters:
      - in: path
        name: id
        description: Id a consultar
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.MedicinaAntecedente'
        "403":
          description: :id  está vacío
    put:
      tags:
      - medicinaAntecedente
      description: actualizar un registro de la tabla MedicinaAntecedente
      operationId: MedicinaAntecedenteController.Put
      parameters:
      - in: path
        name: id
        description: Id del registro a actualizar
        required: true
        type: string
      - in: body
        name: body
        description: Cuerpo para el contenido de MedicinaAntecedente
        required: true
        schema:
          $ref: '#/definitions/models.MedicinaAntecedente'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.MedicinaAntecedente'
        "403":
          description: :id no es entero
    delete:
      tags:
      - medicinaAntecedente
      description: elimina un registro de la tabla MedicinaAntecedente
      operationId: MedicinaAntecedenteController.Delete
      parameters:
      - in: path
        name: id
        description: Id del registro a eliminar
        required: true
        type: string
      responses:
        "200":
          description: '{string} borrado exitoso!'
        "403":
          description: Id vacío
  /medicinaConsultaFisioterapia/:
    get:
      tags:
      - medicinaConsultaFisioterapia
      description: consulta todos los registros de la tabla MedicinaConsultaFisioterapia
      operationId: MedicinaConsultaFisioterapiaController.Get All
      parameters:
      - in: consulta
        name: query
        description: 'Filtro. Por ejemplo, col1: v1, col2: v2 ...'
        type: string
      - in: consulta
        name: fields
        description: Campos devueltos. Por ejemplo, col1, col2 ...
        type: string
      - in: consulta
        name: sortby
        description: Campos ordenados por. Por ejemplo, Col1, col2 ...
        type: string
      - in: consulta
        name: order
        description: El orden correspondiente a cada campo de clasificación, si es un valor único, se aplica a todos los campos de clasificación. Por ejemplo, desc, asc ...
        type: string
      - in: consulta
        name: limit
        description: Limite el tamaño del conjunto de resultados. Debe ser un número entero
        type: string
      - in: consulta
        name: offset
        description: Posición inicial del conjunto de resultados. Debe ser un número entero
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.MedicinaConsultaFisioterapia'
        "403":
          description: ""
    post:
      tags:
      - medicinaConsultaFisioterapia
      description: agregar un registro en la tabla MedicinaConsultaFisioterapia
      operationId: MedicinaConsultaFisioterapiaController.Post
      parameters:
      - in: body
        name: body
        description: Cuerpo para el contenido de MedicinaConsultaFisioterapia
        required: true
        schema:
          $ref: '#/definitions/models.MedicinaConsultaFisioterapia'
      responses:
        "201":
          description: '{int} models.MedicinaConsultaFisioterapia'
        "403":
          description: Cuerpo Vacío
  /medicinaConsultaFisioterapia/{id}:
    get:
      tags:
      - medicinaConsultaFisioterapia
      description: consultar un registro de la tabla MedicinaConsultaFisioterapia por su id
      operationId: MedicinaConsultaFisioterapiaController.Get One
      parameters:
      - in: path
        name: id
        description: Id a consultar
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.MedicinaConsultaFisioterapia'
        "403":
          description: :id está vacío
    put:
      tags:
      - medicinaConsultaFisioterapia
      description: actualizar un registro de la tabla MedicinaConsultaFisioterapia
      operationId: MedicinaConsultaFisioterapiaController.Put
      parameters:
      - in: path
        name: id
        description: Id del registro a actualizar
        required: true
        type: string
      - in: body
        name: body
        description: Cuerpo para el contenido de MedicinaConsultaFisioterapia
        required: true
        schema:
          $ref: '#/definitions/models.MedicinaConsultaFisioterapia'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.MedicinaConsultaFisioterapia'
        "403":
          description: :id no es entero
    delete:
      tags:
      - medicinaConsultaFisioterapia
      description: elimina un registro de la tabla MedicinaConsultaFisioterapia
      operationId: MedicinaConsultaFisioterapiaController.Delete
      parameters:
      - in: path
        name: id
        description: Id del registro a eliminar
        required: true
        type: string
      responses:
        "200":
          description: '{string} borrado exitoso!'
        "403":
          description: Id vacío
  /medicinaDiagnostico/:
    get:
      tags:
      - medicinaDiagnostico
      description: consulta todos los registros de la tabla MedicinaDiagnostico
      operationId: MedicinaDiagnosticoController.Get All
      parameters:
      - in: consulta
        name: query
        description: 'Filtro. Por ejemplo, col1: v1, col2: v2 ...'
        type: string
      - in: consulta
        name: fields
        description: Campos devueltos. Por ejemplo, col1, col2 ...
        type: string
      - in: consulta
        name: sortby
        description: Campos ordenados por. Por ejemplo, Col1, col2 ...
        type: string
      - in: consulta
        name: order
        description: El orden correspondiente a cada campo de clasificación, si es un valor único, se aplica a todos los campos de clasificación. Por ejemplo, desc, asc ...
        type: string
      - in: consulta
        name: limit
        description: Limite el tamaño del conjunto de resultados. Debe ser un número entero
        type: string
      - in: consulta
        name: offset
        description: Posición inicial del conjunto de resultados. Debe ser un número entero
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.MedicinaDiagnostico'
        "403":
          description: ""
    post:
      tags:
      - medicinaDiagnostico
      description: agregar un registro en la tabla MedicinaDiagnostico
      operationId: MedicinaDiagnosticoController.Post
      parameters:
      - in: body
        name: body
        description: Cuerpo para el contenido de MedicinaConsultaFisioterapia
        required: true
        schema:
          $ref: '#/definitions/models.MedicinaDiagnostico'
      responses:
        "201":
          description: '{int} models.MedicinaDiagnostico'
        "403":
          description: Cuerpo Vacío
  /medicinaDiagnostico/{id}:
    get:
      tags:
      - medicinaDiagnostico
      description: consultar un registro de la tabla MedicinaDiagnostico por su id
      operationId: MedicinaDiagnosticoController.Get One
      parameters:
      - in: path
        name: id
        description: Id a consultar
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.MedicinaDiagnostico'
        "403":
          description: :id está vacío
    put:
      tags:
      - medicinaDiagnostico
      description: actualizar un registro de la tabla MedicinaDiagnostico
      operationId: MedicinaDiagnosticoController.Put
      parameters:
      - in: path
        name: id
        description: Id del registro a actualizar
        required: true
        type: string
      - in: body
        name: body
        description: Cuerpo para el contenido de MedicinaConsultaFisioterapia
        required: true
        schema:
          $ref: '#/definitions/models.MedicinaDiagnostico'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.MedicinaDiagnostico'
        "403":
          description: :id no es entero
    delete:
      tags:
      - medicinaDiagnostico
      description: elimina un registro de la tabla MedicinaDiagnostico
      operationId: MedicinaDiagnosticoController.Delete
      parameters:
      - in: path
        name: id
        description: Id del registro a eliminar
        required: true
        type: string
      responses:
        "200":
          description: '{string} borrado exitoso!'
        "403":
          description: Id vacío
definitions:
  models.AccesoHistoriaClinica:
    title: AccesoHistoriaClinica
    type: object
    properties:
      FechaAcceso:
        type: string
        format: datetime
      IdAccesoHistoria:
        type: integer
        format: int64
      IdHistoriaClinica:
        $ref: '#/definitions/models.MedicinaHistoriaClinica'
      ProfesionaId:
        type: integer
        format: int64
  models.MedicinaAntecedente:
    title: MedicinaAntecedente
    type: object
    properties:
      IdHistoriaClinica:
        $ref: '#/definitions/models.MedicinaHistoriaClinica'
      IdMedicinaAntecedente:
        type: integer
        format: int64
      IdTipoAntecedente:
        $ref: '#/definitions/models.MedicinaTipoAntecedente'
      Observaciones:
        type: string
  models.MedicinaConsultaFisioterapia:
    title: MedicinaConsultaFisioterapia
    type: object
    properties:
      Evolucion:
        type: string
      IdHojaHistoria:
        $ref: '#/definitions/models.MedicinaHojaHistoria'
      IdMedicinaConsultaFisioterapia:
        type: integer
        format: int64
      Motivo_consulta:
        type: string
      Observaciones:
        type: string
      PlanManejo:
        type: string
      Valoracion:
        type: string
  models.MedicinaDiagnostico:
    title: MedicinaDiagnostico
    type: object
    properties:
      Activo:
        type: boolean
      Analisis:
        type: string
      Descripcion:
        type: string
      FechaCreacion:
        type: string
        format: datetime
      FechaModificacion:
        type: string
        format: datetime
      IdDiagnosticoMedicina:
        type: integer
        format: int64
      Nombre:
        type: string
      Numero:
        type: integer
        format: int64
      PlanManejo:
        type: string
  models.MedicinaHistoriaClinica:
    title: MedicinaHistoriaClinica
    type: object
    properties:
      IdHistoriaClinica:
        type: integer
        format: int64
      IdTercero:
        type: integer
        format: int64
  models.MedicinaHojaHistoria:
    title: MedicinaHojaHistoria
    type: object
    properties:
      Evolucion:
        type: string
      FechaConsulta:
        type: string
        format: datetime
      IdDiagnostico:
        $ref: '#/definitions/models.MedicinaDiagnostico'
      IdEspecialidad:
        type: integer
        format: int64
      IdHistoriaClinica:
        $ref: '#/definitions/models.MedicinaHistoriaClinica'
      IdHojaHistoria:
        type: integer
        format: int64
      IdPersona:
        type: integer
        format: int64
      IdProfesional:
        type: integer
        format: int64
      Motivo:
        type: string
      Observacion:
        type: string
  models.MedicinaTipoAntecedente:
    title: MedicinaTipoAntecedente
    type: object
    properties:
      Activo:
        type: boolean
      Descripcion:
        type: string
      FechaCreacion:
        type: string
        format: datetime
      FechaModificacion:
        type: string
        format: datetime
      IdTipoAntecedente:
        type: integer
        format: int64
      Nombre:
        type: string
